name: Debug Secret
on:
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check secret
        env:
          MY_SECRET: ${{ secrets.TOKEN_TEST }}
        run: |
          if [ -z "$MY_SECRET" ]; then
            echo "❌ SECRET IS EMPTY"
          else
            echo "✅ Secret exists, length: ${#MY_SECRET}"
          fi
